### PR TITLE
Disable stack protector in newlib

### PR DESCRIPTION
**Pull request by roblabla**

### CODE REVIEW

**Comment by dvdfreitag** [comment]
Once SSP support is merged in the next few days, this PR will become obsolete. Can be merged but it'll just get reverted.

**Comment by Pokemod97** [comment]
What is the difference from this ? https://github.com/reswitched/libtransistor/pull/21

**Comment by dvdfreitag** [comment]
@Pokemod97 There is no difference apart from the fact that `CC_FLAGS` etc has been extracted from `Makefile` and placed into `libtransistor.mk`. Appears this flag was overlooked when that happened.

**Comment by roblabla** [comment]
SSP support got merged, this isn't useful anymore.

**Pull request closed without merging**
