### PR TITLE
Put the main thread handle in the thread context

### PR DESCRIPTION
**Pull request by roblabla**
This is a scaled back version of https://github.com/reswitched/libtransistor/pull/45 that simply adds the thread handle in the libtransistor context. Should be compatible with existing binaries.

### CODE REVIEW

**Comment by misson20000** [comment]
Why is it in all caps?

**Comment by roblabla** [comment]
Aren't globals supposed to be in all-caps ?

**Comment by misson20000** [comment]
Personally would rather reserve all caps for macros and enums and such.

**Comment by roblabla** [comment]
Also should I bump the libtransistor context version ?

**Comment by misson20000** [comment]
Yes, the version should be incremented so the existence of the thread id field can be tested

**Pull request merged**
