### PR TITLE
add args command to ace_loader

### PR DESCRIPTION
**Pull request by misson20000**

### CODE REVIEW

**Comment by kgsws** [comment]
Calling "args" without any parameters would cause NULL pointer dereference. Use same check as in "exec".

Calling "exec" would set those values for any newly pushed NROs, it's not an issue, just a remainder.

**Comment by misson20000** [comment]
hmm, shouldn't we change it to pass an empty string instead of a null pointer if there are no arguments?

**Comment by kgsws** [comment]
I find null pointer a better solution, i mean, it is a simple 'if' on pointer itself rather than dereferencing it first.
As you can see from other commands, null pointer check is used to print somewhat specific 'help' for each command that requires parameters. Your command would just print something similar too.
I can't really imagine why would empty string be better for that.

**Comment by misson20000** [comment]
Empty string makes more sense to me. It's like "there could be arguments, but there aren't any" rather than "there were never arguments here in the first place". It makes the check to see if there are any arguments into a check to see if we have any arguments, rather than a check to see if something passed us NULL for some reason. When you slice a string like "exec " by a space, you get "exec" and an empty string, not "exec" and NULL. That's just the way it makes sense to me. If you disagree I'd be happy to just implement a null pointer check

**Comment by kgsws** [comment]
Command server handler here is not bash-style. If you run command without parameters, your function will get called with NULL. If you run command with parameter, you get only pointer to parameter itself, not a command name.
I just like that there is no need to dereference this pointer to check if there are no parameters - it's one step less for code to do.

Anyway, i like your solution - print current command line, that makes perfect sense.
Just a note: my arg parser is very simple and does not support quoting.

**Pull request merged**
